import React from 'react'

import classNames from 'classnames'
import type { Metadata } from 'next'
import { Rajdhani } from 'next/font/google'
import './globals.scss'

const rajdhani = Rajdhani({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-rajdhani',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classNames(rajdhani.className, rajdhani.variable)}>
        {children}
      </body>
    </html>
  )
}
